"""Tests for nsight_parser.py: CSV slicing + entry-point smoke tests."""

from __future__ import annotations

import csv
from pathlib import Path

from vernier_tools.benchmarking import nsight_parser


# --------------------------------------------------------------------------- #
# _iter_csv_after_header strips the multi-line banner that nsys / ncu print  #
# --------------------------------------------------------------------------- #


def test_iter_csv_skips_banner() -> None:
    text = """\
*** Performance counter data ***
Generated by nsys 2025.1

Time (%),Total Time (ns),Instances,Avg (ns),Name
40.1,200000,10,20000,kernel_a
35.6,180000,10,18000,kernel_b
"""
    rows = list(nsight_parser._iter_csv_after_header(text))
    assert len(rows) == 2
    assert rows[0]["Name"] == "kernel_a"
    assert rows[0]["Time (%)"] == "40.1"
    assert rows[1]["Instances"] == "10"


def test_iter_csv_returns_empty_when_no_header() -> None:
    text = "no comma-separated content here"
    assert list(nsight_parser._iter_csv_after_header(text)) == []


# --------------------------------------------------------------------------- #
# ParseResult.write_csv: stable column order, empty inputs still write file  #
# --------------------------------------------------------------------------- #


def test_write_csv_orders_known_columns_first(tmp_path: Path) -> None:
    result = nsight_parser.ParseResult(
        rows=[
            {
                "source": "nsys",
                "report": "cuda_gpu_kern_sum",
                "kernel": "kernel_a",
                "instances": "10",
                "time_total_ns": "200000",
                "time_avg_ns": "20000",
                "time_pct": "40.1",
                "extra_metric": "0.5",
            }
        ]
    )
    out = tmp_path / "nsight.csv"
    result.write_csv(out)
    with out.open() as f:
        reader = csv.reader(f)
        header = next(reader)
    assert header[:7] == [
        "source",
        "report",
        "kernel",
        "instances",
        "time_total_ns",
        "time_avg_ns",
        "time_pct",
    ]
    assert "extra_metric" in header


def test_write_csv_empty_rows_still_creates_file(tmp_path: Path) -> None:
    result = nsight_parser.ParseResult(rows=[])
    out = tmp_path / "empty.csv"
    result.write_csv(out)
    assert out.exists()
    assert out.read_text() == ""


# --------------------------------------------------------------------------- #
# parse_paths: walks directories, warns when no inputs match                  #
# --------------------------------------------------------------------------- #


def test_parse_paths_no_inputs_warns(tmp_path: Path) -> None:
    result = nsight_parser.parse_paths([tmp_path])
    assert result.rows == []
    assert any("no .nsys-rep" in w for w in result.warnings)


# --------------------------------------------------------------------------- #
# main() returns 0 on a clean parse                                          #
# --------------------------------------------------------------------------- #


def test_main_parse_empty_dir(tmp_path: Path) -> None:
    out = tmp_path / "x.csv"
    rc = nsight_parser.main(["parse", str(tmp_path), "--csv", str(out)])
    assert rc == 0
    assert out.exists()


# --------------------------------------------------------------------------- #
# _clean_key normalizes ncu's spacey/parens/slashy column names               #
# --------------------------------------------------------------------------- #


def test_clean_key_normalizes() -> None:
    assert nsight_parser._clean_key("SM Throughput (% peak)") == "sm_throughput_%_peak"
    assert nsight_parser._clean_key("DRAM Bytes/sec") == "dram_bytes_per_sec"
